### ISSUE TITLE
New addresses

### ISSUE THREAD

**Issue by inlinecoder** [ognus/wallet-address-validator#12]
Can you add ETH and some other currencies to be supported? Or, merge this https://github.com/ForQuest/wallet-address-validator ?

**Comment by ognus** [comment]
@inlinecoder Yes, I am actually working on it + some clean up and refactor of the whole module. ETH and other ethereum "variants" will be available within a day or two.

**Comment by inlinecoder** [comment]
@ognus thanks for the update! Glad to hear that.

**Comment by ognus** [comment]
New version released: `0.1.3`, it has ETH and it's forks coins as well as DigiByte.
