### ISSUE TITLE
other cryptocurrencies addresses

### ISSUE THREAD

**Issue by Naveedali1234** [ognus/wallet-address-validator#15]
hello!!

I really apreciate your efforts for this package. 
actually i have 102 cryptocurrencies, how can i validate all the crypto wallet addresses if a user type any of the crypto wallet address? can i use this package for crypto currencies other than mentioned on the doc?
If yes, then how can i achieve this?

Your help would be really appreciated.

Kind regards

**Comment by ognus** [comment]
Hi, thank you @Naveedali1234 .

You can only validate the coins listed in the docs.

Have a look at the source code here: https://github.com/ognus/wallet-address-validator/blob/master/src/currencies.js. For most altcoins the validation is the same as Bitcoin (details https://en.bitcoin.it/wiki/Base58Check_encoding) but the version byte is different. As you can see the `currencies.js` file just contains a mapping from human readable coins names to the version bytes.

So what you probably need to, is to support all of those different version bytes. That's probably the best list of all the bytes used by different altcoin https://github.com/libbitcoin/libbitcoin/wiki/Altcoin-Version-Mappings

Hth, good luck.
