### ISSUE TITLE
Segwit support

### ISSUE THREAD

**Issue by deefactorial** [ognus/wallet-address-validator#16]
Segwit addresses fail. https://en.bitcoin.it/wiki/Bech32

ie If I run `valid('bc1qar0srrr7xfkvy5l643lydnw9re59gtzzwf5mdq', 'bitcoin');` I get an invalid address when in fact it is a valid address.

**Comment by ognus** [comment]
Not sure how to go about it yet. Good start would be

https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki#Bech32
and
https://github.com/sipa/bech32/tree/master/ref/javascript

**Comment by ulich-trade** [comment]
@deefactorial @ognus Hi guys! Any updates?

**Comment by ognus** [comment]
@ulich-trade not much going on with this one atm, I might have a look at it some time later, but don't have specific plans...
