### ISSUE TITLE
Add ripple and dash

### ISSUE THREAD

**Issue by miranos** [ognus/wallet-address-validator#17]
Hi

Is there a way to add Dash and Ripple please ?
Or give me advice on how to add them.

Thank you

**Comment by dpominov** [comment]
For Ripple i did PR #18

**Comment by ognus** [comment]
@dpominov Thank you :) Will add Dash and make release tomorrow or so.

**Comment by ognus** [comment]
@dpominov Added Dash and released `0.1.4`. Thanks!
