### ISSUE TITLE
Binding of function before exporting

### ISSUE THREAD

**Issue by nicklatkovich** [ognus/wallet-address-validator#22]
It would be nice to implement binding functions before export them, so that you could use either:
`const { validate: isAddressCorrect } = require('wallet-address-validator');`
Now it gives exception:
`TypeError: this.getAddressType is not a function`
Because the context is not bind to the exported object.

**Comment by ognus** [comment]
Thanks @nicklatkovich. Fixed and released `0.1.6`.
