### ISSUE TITLE
JAVA version of this awesome work ?

### ISSUE THREAD

**Issue by miranos** [ognus/wallet-address-validator#23]
Hi,

Is there a way to convert this awesome work to JAVA please ?

If yes, any help ?

**Comment by ognus** [comment]
@miranos I don't think you can automatically "convert" this code to Java, if that's what you are asking for.

I think the best you can do is to rewrite this codebase to Java. If you know both Java and Javascript this shouldn't be too hard.

Alternatively you can try using Java's `ScriptEngineManager` (https://docs.oracle.com/javase/6/docs/technotes/guides/scripting/programmer_guide/index.html) to run the Javascript code on JVM.
