### ISSUE TITLE
Monero address validator

### ISSUE THREAD

**Issue by ghanavati27** [ognus/wallet-address-validator#28]
Good work!
Also, add monero address validator.

**Comment by ghanavati27** [comment]
I saw good source code In paython , take a look.
Source code: https://github.com/emesik/monero-python/blob/master/monero/address.py
Home page: http://monero-python.readthedocs.io/en/latest/
Examples: http://monero-python.readthedocs.io/en/latest/address.html

**Comment by ognus** [comment]
@ghanavati27 thanks, will have a look

**Comment by ddinhtb** [comment]
Double this. Also Stellar please
