### ISSUE TITLE
RegEx improvement

### ISSUE THREAD

**Issue by mrqc** [ognus/wallet-address-validator#33]
Hi!
Good work. The ripple regex:

var ALLOWED_CHARS = 'rpshnaf39wBUDNEGHJKLM4PQRST7VWXYZ2bcdeCg65jkm8oFqi1tuvAxyz';

can be rewritten as "[1-9A-HJ-NP-Za-km-z]".

**Comment by ognus** [comment]
@mrqc Hi :) clever and easier to read, thanks! Have other priorities atm, so will postpone that for later.

**Comment by mrqc** [comment]
I created a pull request.
