### ISSUE TITLE
Cannot validate testnet LTC address with prefix "Q"

### ISSUE THREAD

**Issue by 150grism** [ognus/wallet-address-validator#37]
For example, address: QjpzxpbLp5pCGsCczMbfh1uhC3P89QZavY.

**Comment by ognus** [comment]
@150grism Thanks.

I tried calling `.validate('QjpzxpbLp5pCGsCczMbfh1uhC3P89QZavY', 'LTC', 'testnet')
` and it returns `true`. Was that not working for you?

**Comment by 150grism** [comment]
@ognus absolutely you are right, my bad - forgot to update the package ><

**Comment by ognus** [comment]
@150grism no worries, thank you for letting me know 👍 Closing the issue.
