### ISSUE TITLE
Bech32 addresses for testnet and mainnet

### ISSUE THREAD

**Issue by mbnissen** [ognus/wallet-address-validator#61]
https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki

As stated here bech32 address uses "bc" for mainnet and "tb" for testnet.

This library marks both to be valid in both testnet and mainnet

**Comment by valyakin** [comment]
Yes, I faced the same problem

**Comment by crabvk** [comment]
That's because of
https://github.com/ognus/wallet-address-validator/blob/bcd0c8f448754fc120c9e4591bc7680a58e83e06/src/crypto/segwit_addr.js#L73-L88
which tries both prefixes, `bc` and `tb`.

**Comment by crabvk** [comment]
Also, I think we should check [address prefix](https://en.bitcoin.it/wiki/List_of_address_prefixes) before making any further calculations.

**Comment by jonathascarrijo** [comment]
#70 seems to fix this.
