### ISSUE TITLE
Can we validate Bitcoin SV addresses using this?

### ISSUE THREAD

**Issue by schadokar** [ognus/wallet-address-validator#75]
I tried to validate the BSV address using the wallet-address-validator. It succeed when I passed the BTC as currency.  

So, it is to confirm, Will it work for all the BSV addresses or there are some technical differences in these 2?  

Can you please update the readme like it will work for BSV also?

**Comment by deefactorial** [comment]
BSV is a fork of BCH which uses the BTC address format.

**Comment by schadokar** [comment]
thank you
